// Push UI Kit theme configuration for GameTribe
export const gameTribeTheme = {
  borderRadius: {
    ChatView: '16px',
    chatProfile: '12px',
    messageInput: '12px',
    searchInput: '12px',
    modal: '16px',
    modalInnerComponents: '8px',
  },
  backgroundColor: {
    ChatViewBackground: 'rgba(18, 18, 24, 0.95)',
    chatProfileBackground: 'rgba(55, 65, 81, 0.8)',
    messageInputBackground: 'rgba(55, 65, 81, 0.6)',
    chatSentBubbleBackground: '#6366f1', // primary-500 equivalent
    chatReceivedBubbleBackground: 'rgba(55, 65, 81, 0.8)',
    encryptionMessageBackground: 'rgba(55, 65, 81, 0.4)',
    buttonBackground: '#6366f1',
    modalBackground: 'rgba(18, 18, 24, 0.95)',
    criteriaLabelBackground: 'rgba(55, 65, 81, 0.6)',
    modalInputBackground: 'rgba(55, 65, 81, 0.4)',
    modalHoverBackground: 'rgba(55, 65, 81, 0.8)',
    buttonDisableBackground: '#6b7280',
    toastSuccessBackground: '#10b981',
    toastErrorBackground: '#ef4444',
    toastShadowBackground: '#00000020',
  },
  fontSize: {
    chatProfileText: '16px',
    messageInputText: '14px',
    chatSentBubbleText: '14px',
    chatReceivedBubbleText: '14px',
    timestamp: '12px',
    encryptionMessageText: '12px',
    chatReceivedBubbleAddressText: '12px',
    chatReceivedBubbleTimestampText: '12px',
    chatSentBubbleTimestampText: '12px',
    searchInputText: '14px',
    searchPlaceholderText: '14px',
  },
  fontWeight: {
    chatProfileText: '500',
    messageInputText: '400',
    chatSentBubbleText: '400',
    chatReceivedBubbleText: '400',
    timestamp: '300',
    encryptionMessageText: '400',
    chatReceivedBubbleAddressText: '300',
    chatReceivedBubbleTimestampText: '400',
    chatSentBubbleTimestampText: '400',
    searchInputText: '400',
    searchPlaceholderText: '400',
  },
  fontFamily: 'Inter, system-ui, sans-serif',
  border: {
    ChatView: '1px solid rgba(55, 65, 81, 0.3)',
    chatProfile: '1px solid rgba(55, 65, 81, 0.3)',
    messageInput: '1px solid rgba(55, 65, 81, 0.3)',
    searchInput: '1px solid transparent',
    modal: 'none',
    modalInnerComponents: '1px solid rgba(55, 65, 81, 0.3)',
  },
  iconColor: {
    emoji: '#9ca3af',
    attachment: '#9ca3af',
    sendButton: '#ffffff',
    groupSettings: '#9ca3af',
  },
  textColor: {
    chatProfileText: '#ffffff',
    messageInputText: '#ffffff',
    chatSentBubbleText: '#ffffff',
    chatReceivedBubbleText: '#ffffff',
    timestamp: '#9ca3af',
    encryptionMessageText: '#9ca3af',
    buttonText: '#ffffff',
    chatReceivedBubbleAddressText: '#9ca3af',
    chatReceivedBubbleTimestampText: '#9ca3af',
    chatSentBubbleTimestampText: '#9ca3af',
    searchInputText: '#ffffff',
    searchPlaceholderText: '#9ca3af',
    modalHeadingText: '#ffffff',
    modalSubHeadingText: '#9ca3af',
    buttonDisableText: '#6b7280',
  },
  backdropFilter: 'blur(10px)',
  spinnerColor: '#6366f1',
  scrollbarColor: '#6366f1',
};
